name: release

on:
  push:
    tags:
      - "*"

jobs:
  build-linux-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev libreadline-dev libusb-1.0-0-dev libtool automake autoconf gcc make g++ libzip-dev patch file bash
        shell: bash
      - name: prepare environment
        run: |
          echo "target_triplet=`gcc -dumpmachine`" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1
      - name: run build script
        run: |
          cd ./script
          sudo chmod +x ./build-ubuntu.sh
          sudo ./build-ubuntu.sh
        shell: bash
      - name: prepare artifact
        working-directory: .
        run: |
          mkdir -p ${{ github.workspace }}/dest
          tar -C ${{ github.workspace }}/dest -cf tsschecker-latest_${{env.target_triplet}}.tar /usr/local/bin/tsschecker
      - name: create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
            ${{ github.workspace }}/dest/tsschecker-latest_${{env.target_triplet}}.tar
